import { GoogleGenerativeAI } from "@google/generative-ai";
import { MeetingMetadata } from '../types';

// Helper to convert Blob to Base64
export const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = (reader.result as string).split(',')[1];
      resolve(base64String);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

export const transcribeAudio = async (audioBlob: Blob): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing.");
  }

  const genAI = new GoogleGenerativeAI(process.env.API_KEY);
  const base64Audio = await blobToBase64(audioBlob);

  try {
    // Use the correct model name format
    const model = genAI.getGenerativeModel({ model: "models/gemini-1.5-pro" });
    
    const prompt = "Please generate a verbatim transcription of this meeting audio. Identify different speakers if possible (e.g., Speaker 1, Speaker 2). Return ONLY the transcription texts, no preamble.";
    
    const result = await model.generateContent([
      prompt,
      {
        inlineData: {
          data: base64Audio,
          mimeType: audioBlob.type || 'audio/webm'
        }
      }
    ]);
    
    return result.response.text() || "No transcription generated.";
  } catch (error) {
    console.error("Transcription error:", error);
    throw new Error("Failed to transcribe audio. Please check your internet connection and try again.");
  }
};

export const generateMeetingMinutes = async (transcript: string, metadata: MeetingMetadata): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing.");
  }

  const genAI = new GoogleGenerativeAI(process.env.API_KEY);
  // Use the correct model name format
  const model = genAI.getGenerativeModel({ model: "models/gemini-1.5-pro" });

  const prompt = `
    You are Zayna, an expert executive assistant. Create a highly detailed, professional, and actionable Meeting Minutes (MoM) document based on the provided transcript and meeting details.
    
    *** MEETING DETAILS ***
    Title: ${metadata.title}
    Agenda: ${metadata.agenda}
    Location: ${metadata.location}
    Date/Time: ${metadata.dateTime}
    Attendees: ${metadata.attendees}

    *** TRANSCRIPT ***
    ${transcript}

    *** INSTRUCTIONS FOR FORMATTING ***
    Produce the output in clean, structured Markdown. Use the following structure:

    # ${metadata.title} - Meeting Minutes
    
    ## 1. Executive Summary
    (A concise paragraph summarizing the main purpose, tone, and outcome of the meeting).

    ## 2. Key Discussion Points
    (Detailed bullet points of what was discussed. Group related topics together).

    ## 3. Action Items
    (MUST be a Markdown Table with columns: **Task Description** | **Owner** | **Priority** | **Deadline**).
    If no deadline is mentioned, suggest "TBD" or infer "ASAP" based on urgency.

    ## 4. Key Decisions Made
    (List of agreements or final decisions).

    ## 5. Next Steps & Follow-up
    (What happens next? When is the next meeting?).

    Tone: Professional, Clear, Concise, and Action-Oriented.
  `;

  try {
    const result = await model.generateContent(prompt);
    return result.response.text() || "Failed to generate MoM.";
  } catch (error) {
    console.error("MoM generation error:", error);
    throw new Error("Failed to generate Meeting Minutes.");
  }
};

export const generateEmailDraft = async (mom: string, metadata: MeetingMetadata): Promise<string> => {
    if (!process.env.API_KEY) {
      throw new Error("API Key is missing.");
    }
  
    const genAI = new GoogleGenerativeAI(process.env.API_KEY);
    // Use the correct model name format
    const model = genAI.getGenerativeModel({ model: "models/gemini-1.5-pro" });
  
    const prompt = `
      Based on the following Meeting Minutes, write a professional follow-up email to the attendees.
      
      *** MEETING MINUTES ***
      ${mom}
      
      *** INSTRUCTIONS ***
      - Subject Line is already handled, just provide the BODY of the email.
      - Start with a professional greeting.
      - Summarize the key outcomes briefly (1-2 sentences).
      - List the Action Items clearly (bullet points).
      - Close professionally.
      - Do not use markdown bolding/formatting that might break in plain text emails, keep it clean.
      - Sign off as "Generated by Zayna".
    `;
  
    try {
      const result = await model.generateContent(prompt);
      return result.response.text() || "Please find the meeting minutes attached.";
    } catch (error) {
      console.error("Email generation error:", error);
      return "Here are the minutes from our meeting.";
    }
  };

export const translateText = async (text: string, targetLangName: string): Promise<string> => {
  if (!process.env.API_KEY) {
      throw new Error("API Key is missing.");
  }

  const genAI = new GoogleGenerativeAI(process.env.API_KEY);
  // Use the correct model name format
  const model = genAI.getGenerativeModel({ model: "models/gemini-1.5-pro" });

  const prompt = `
      Translate the following text into ${targetLangName}. 
      Input Text: "${text}"
      
      Instructions:
      1. Provide ONLY the translated text. 
      2. Do not add explanations, quotes, or notes.
      3. Maintain the original tone and meaning.
      4. If the text is already in ${targetLangName}, return it as is.
  `;

  try {
      const result = await model.generateContent(prompt);
      return result.response.text()?.trim() || text;
  } catch (error) {
      console.error("Translation error:", error);
      return text;
  }
};